spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db2
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    jdbc:
      initialize-schema: always
#server:
#  servlet:
#    session:
#      timeout: 60s

application:
  bcrypt:
    strength: 12
  specialCharacters: " !#$%&'()*+,-./:;<=>?@[]^_`{|}~"